# KAN-165: install-time setup for the local HTTPS UI.
#
# Dot-sourced by install-release.ps1 (and the uninstaller). Provides:
#   Install-LocalHttpsUi   — generate the per-host cert, trust it in the
#                            Windows machine Root store, add the hosts-file
#                            entry, and seed the user-editable launcher config.
#   Uninstall-LocalHttpsUi — untrust the cert and remove the hosts-file entry.
#
# The certificate + private key are generated by the agent itself (Node) so
# there is exactly one code path for cert generation. NOTHING secret is shipped
# in the (public) repo — every install mints its own key.

$script:LocalUiDomain = "local.printanywhere.dhruvantasystems.com"
$script:HostsSentinel = "# PrintAnywhereAgent (KAN-165) — local UI domain"

function Get-HostsFilePath {
    return Join-Path $env:SystemRoot "System32\drivers\etc\hosts"
}

# Generate (or reuse) the per-host certificate AND seed the launcher config by
# invoking the agent's dedicated, built provisioning entry point. Invoking a
# plain file path (no inline -e snippet, no temp file) avoids the Windows
# absolute-path ESM import trap. Returns the parsed JSON with certPath +
# thumbprint, both inside the agent data directory.
function Invoke-AgentLocalUiProvisioning {
    param(
        [string]$NodeCommand,
        [string]$RepoRoot,
        [string]$DataDir
    )

    $entryPoint = Join-Path $RepoRoot "dist\install\provisionLocalUi.js"
    if (-not (Test-Path $entryPoint)) {
        throw "Local UI provisioning entry point is missing: $entryPoint. Rebuild the release bundle."
    }

    $output = & $NodeCommand $entryPoint $DataDir
    if ($LASTEXITCODE -ne 0) {
        throw "Agent local UI provisioning failed (exit $LASTEXITCODE)."
    }
    return ($output | ConvertFrom-Json)
}

# Trust the generated certificate in the Windows machine Root store so the
# operator's browser shows no warning for the local UI. Idempotent: certutil
# -addstore -f replaces any prior copy of the same cert.
function Add-LocalUiCertToTrustStore {
    param([string]$CertPath)

    if (-not (Test-Path $CertPath)) {
        Write-Warning "Local UI certificate not found at $CertPath — skipping trust-store import."
        return
    }
    & certutil -f -addstore Root "$CertPath" | Out-Null
    if ($LASTEXITCODE -ne 0) {
        Write-Warning "Could not import the local UI certificate into the machine Root store. The console will still work, but the browser may show a certificate warning."
    } else {
        Write-Host "Trusted the local UI certificate in the Windows machine Root store."
    }
}

# Remove the trusted certificate by thumbprint at uninstall time so no stale
# trusted cert is left behind on the machine.
function Remove-LocalUiCertFromTrustStore {
    param([string]$Thumbprint)

    if ([string]::IsNullOrWhiteSpace($Thumbprint)) {
        return
    }
    & certutil -delstore Root "$Thumbprint" | Out-Null
    # A non-zero exit just means the cert was already gone — non-fatal.
}

# Add `127.0.0.1 local.printanywhere.dhruvantasystems.com` to the hosts file.
# Idempotent (sentinel-guarded). The hosts entry is the reliable name-resolution
# mechanism — it is immune to router DNS-rebinding protection that strips public
# DNS records pointing at 127.0.0.1.
function Add-LocalUiHostsEntry {
    $hostsPath = Get-HostsFilePath
    if (-not (Test-Path $hostsPath)) {
        Write-Warning "Hosts file not found at $hostsPath — skipping hosts entry."
        return
    }

    $lines = Get-Content -LiteralPath $hostsPath -ErrorAction SilentlyContinue
    foreach ($line in $lines) {
        if ($line -match [Regex]::Escape($script:LocalUiDomain)) {
            Write-Host "Hosts entry for $($script:LocalUiDomain) already present."
            return
        }
    }

    try {
        Add-Content -LiteralPath $hostsPath -Value @(
            "",
            $script:HostsSentinel,
            "127.0.0.1 $($script:LocalUiDomain)"
        )
        Write-Host "Added hosts entry: 127.0.0.1 $($script:LocalUiDomain)"
    } catch {
        Write-Warning "Could not write the hosts entry (administrator rights are required). The console will still work at https://127.0.0.1:<port>."
    }
}

# Remove the sentinel-marked hosts entry at uninstall time.
function Remove-LocalUiHostsEntry {
    $hostsPath = Get-HostsFilePath
    if (-not (Test-Path $hostsPath)) {
        return
    }
    try {
        $lines = Get-Content -LiteralPath $hostsPath
        $kept = $lines | Where-Object {
            ($_ -ne $script:HostsSentinel) -and
            -not ($_ -match [Regex]::Escape($script:LocalUiDomain))
        }
        Set-Content -LiteralPath $hostsPath -Value $kept -Encoding ASCII
    } catch {
        Write-Warning "Could not remove the hosts entry for $($script:LocalUiDomain)."
    }
}

# Top-level install entry point.
function Install-LocalHttpsUi {
    param(
        [string]$NodeCommand,
        [string]$RepoRoot,
        [string]$DataDir
    )

    Write-Host "Setting up the secure local console (HTTPS)..."
    # Mints the per-host cert + key and seeds ui-launcher.json in one call.
    $cert = Invoke-AgentLocalUiProvisioning -NodeCommand $NodeCommand -RepoRoot $RepoRoot -DataDir $DataDir
    Add-LocalUiCertToTrustStore -CertPath $cert.certPath
    Add-LocalUiHostsEntry
}

# Top-level uninstall entry point.
function Uninstall-LocalHttpsUi {
    param([string]$DataDir)

    $thumbprintPath = Join-Path $DataDir "tls\local-ui-thumbprint.txt"
    if (Test-Path $thumbprintPath) {
        $thumbprint = (Get-Content -LiteralPath $thumbprintPath -Raw).Trim()
        Remove-LocalUiCertFromTrustStore -Thumbprint $thumbprint
    }
    Remove-LocalUiHostsEntry
}
