import { PDFDocument, rgb, StandardFonts, degrees } from 'pdf-lib'

export interface CoverPageOptions {
  businessName: string
  /** If provided and reachable, embedded as a PNG or JPEG image above the name. */
  logoUrl?: string | null
  /** Injected into the sub-line, e.g. "Powered by PrintAnywhere". */
  tagline?: string
}

/**
 * Builds a PDF Buffer with one cover page containing the business name and
 * an optional logo, then merges the original job PDF after it.
 */
export async function prependCoverPage(jobPdfBytes: Buffer, options: CoverPageOptions): Promise<Buffer> {
  const { businessName, logoUrl, tagline = 'Powered by PrintAnywhere' } = options

  // Build single-page cover document
  const coverDoc = await PDFDocument.create()
  const page = coverDoc.addPage()
  const { width, height } = page.getSize()

  const font = await coverDoc.embedFont(StandardFonts.HelveticaBold)
  const regularFont = await coverDoc.embedFont(StandardFonts.Helvetica)

  const green = rgb(0.094, 0.302, 0.192) // #184d31

  // Background strip at top
  page.drawRectangle({
    x: 0,
    y: height - 120,
    width,
    height: 120,
    color: green,
  })

  // "PrintAnywhere" header text in strip
  page.drawText('PrintAnywhere', {
    x: 36,
    y: height - 72,
    size: 28,
    font,
    color: rgb(1, 1, 1),
  })

  // Separator line
  page.drawLine({
    start: { x: 36, y: height - 150 },
    end: { x: width - 36, y: height - 150 },
    thickness: 1,
    color: rgb(0.8, 0.8, 0.8),
  })

  let logoBottom = height - 190

  // Optional logo image
  if (logoUrl) {
    try {
      const logoBytes = await fetchBytes(logoUrl)
      if (logoBytes) {
        let logoImage
        const header = logoBytes.slice(0, 4)
        const isPng = header[0] === 0x89 && header[1] === 0x50
        if (isPng) {
          logoImage = await coverDoc.embedPng(logoBytes)
        } else {
          logoImage = await coverDoc.embedJpg(logoBytes)
        }
        const maxW = 180
        const maxH = 80
        const scale = Math.min(maxW / logoImage.width, maxH / logoImage.height, 1)
        const logoW = logoImage.width * scale
        const logoH = logoImage.height * scale
        page.drawImage(logoImage, {
          x: 36,
          y: logoBottom - logoH,
          width: logoW,
          height: logoH,
        })
        logoBottom = logoBottom - logoH - 16
      }
    } catch {
      // Logo fetch failed — proceed without it
    }
  }

  // Business name
  const nameSize = businessName.length > 30 ? 28 : 36
  page.drawText(businessName, {
    x: 36,
    y: logoBottom - nameSize - 4,
    size: nameSize,
    font,
    color: green,
  })

  // Tagline
  page.drawText(tagline, {
    x: 36,
    y: logoBottom - nameSize - 36,
    size: 14,
    font: regularFont,
    color: rgb(0.4, 0.4, 0.4),
  })

  // Footer
  const footerText = `Document generated by PrintAnywhere · ${new Date().toLocaleDateString()}`
  const footerWidth = regularFont.widthOfTextAtSize(footerText, 9)
  page.drawText(footerText, {
    x: (width - footerWidth) / 2,
    y: 28,
    size: 9,
    font: regularFont,
    color: rgb(0.6, 0.6, 0.6),
  })

  const coverBytes = await coverDoc.save()

  // Merge: cover first, then all job pages
  const merged = await PDFDocument.create()
  const coverLoaded = await PDFDocument.load(coverBytes)
  const jobLoaded = await PDFDocument.load(jobPdfBytes)

  const [coverPageCopy] = await merged.copyPages(coverLoaded, [0])
  merged.addPage(coverPageCopy)

  const jobPageIndices = jobLoaded.getPageIndices()
  const jobPageCopies = await merged.copyPages(jobLoaded, jobPageIndices)
  for (const p of jobPageCopies) merged.addPage(p)

  const mergedBytes = await merged.save()
  return Buffer.from(mergedBytes)
}

async function fetchBytes(url: string): Promise<Uint8Array | null> {
  const controller = new AbortController()
  const timeout = setTimeout(() => controller.abort(), 5000)
  try {
    const res = await fetch(url, { signal: controller.signal })
    if (!res.ok) return null
    const buf = await res.arrayBuffer()
    return new Uint8Array(buf)
  } catch {
    return null
  } finally {
    clearTimeout(timeout)
  }
}
